DjangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('DjangoProjectApp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DjangoProjectApp/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static


from .views import (
    AuthenticationView,
    delete_film,
    like_film,
    # MainView,
    main_page,
    profile_page,
    SignupView,
    AddFilmView,
    # FilmDetailView,
    FilmDetail,
    logout_page,
    # about,
    # cart,
    # contact,
    # privacy,
    # ShopView,
    # blog,
    # CreateAddressView,
    # AddressView,
    # process_order,
)

urlpatterns = [
    path("", main_page, name="main_page"),
    path("profile/", profile_page, name="profile_page"),
    path("add_film/", AddFilmView.as_view(), name="add_film"),
    path('film/<slug:slug>/delete/', delete_film, name='delete_film'),
    path("film/<slug:slug>/", FilmDetail, name="film_detail"),
    path('like_film/', like_film, name='like_film'),
    # path("about/", about, name="about_page"),
    # path("cart/", cart, name="cart_page"),
    # path("contact/", contact, name="contact_page"),
    # path("privacy", privacy, name="privacy_page"),
    # path("shop/", ShopView.as_view(), name="shop_page"),
    # path("blog/", blog, name="blog_page"),
    path("signup/", SignupView.as_view(), name="signup"),
    path("login/", AuthenticationView.as_view(), name="login"),
    path("logout/", logout_page, name="logout"),
    # path("address/", AddressView.as_view(), name="address-list"),
    # path("address/create/", CreateAddressView.as_view(), name="address_new"),
    # path("process_order/", process_order, name="process_order"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

DjangoProjectApp/models/films.py
from django.db import models
from django.urls import reverse
from pytils.translit import slugify

class Film(models.Model):
    title = models.CharField(max_length=32)
    description = models.TextField()
    image = models.ImageField(upload_to="")
    year_created = models.IntegerField()
    genres = models.ManyToManyField("Genre", through="MovieGenre", through_fields=("film", "genre"), related_name="films")
    slug = models.SlugField(unique=True)
    prepopulated_fields = {"slug": ("title", )}

    def get_absolute_url(self):
        return reverse('film_detail', kwargs={'slug': self.slug})
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Film, self).save(*args, **kwargs)
        

class Genre(models.Model):
    name = models.CharField(max_length=30)
    def __str__(self):
        return self.name

class MovieGenre(models.Model):
    film = models.ForeignKey(Film, on_delete=models.CASCADE, related_name="genre_set")
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE, related_name="film_set")

DjangoProjectApp/models/user.py
from django.db import models
from django.contrib.auth.models import (
    AbstractBaseUser,
    PermissionsMixin,
    BaseUserManager,
)
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from django.contrib.auth.models import Group, Permission

from DjangoProjectApp.models.films import Film


class UserManager(BaseUserManager):
    def create_user(
        self,
        # email,
        username,
        password,
        # phone_number,
        # birthday_date,
                # gender,
    ) -> "User":
        # if not email:
        #     raise ValueError("An email is required.")
        if not password:
            raise ValueError("A password is required.")
        # email = self.normalize_email(email)
        user = self.model(
            # email=email,
            username=username,
            password=password,
            # phone_number=phone_number,
            # birthday_date=birthday_date,
                    # gender=gender,
        )
        user.set_password(password)
        user.save()
        return user

    def create_superuser(
        self,
        # email,
        username,
        password,
        # phone_number,
        # birthday_date,
                # gender,
    ) -> "User":
        # if not email:
        #     raise ValueError("An email is required.")
        if not password:
            raise ValueError("A password is required.")
        # email = self.normalize_email(email)
        user = self.model(
            # email=email,
            username=username,
            password=password,
            # phone_number=phone_number,
            # birthday_date=birthday_date,
                    # gender=gender,
        )
        user.is_superuser = True
        # user.is_staff = True
        user.is_active = True

        user.save()
        return user


class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(_("username"), max_length=15, unique=True)
    likes_lst = models.ManyToManyField(Film, through="Like", through_fields=("user", "film"))
    objects = UserManager()
    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = [
    ]

    def get_username(self):
        return f"{self.username}"
    
    @property
    def liked_films(self):
        return Film.objects.filter(likes__user=self)

    def like_film(self, film):
        like = Like.objects.get_or_create(user=self, film=film)
        return like

    def unlike_film(self, film):
        Like.objects.filter(user=self, film=film).delete()

    def has_liked(self, film):
        return Like.objects.filter(user=self, film=film).exists()

    
class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='likes')
    film = models.ForeignKey(Film, on_delete=models.CASCADE, related_name='likes')

    class Meta:
        unique_together = ('user', 'film',)

DjangoProjectApp/forms.py
from .models import Film, User, Genre
from typing import Any
from django.contrib.auth.forms import (
    BaseUserCreationForm,
    UserCreationForm,
    AuthenticationForm,
)
from django.contrib.auth import get_user_model
from django.forms import (
    CharField,
    ChoiceField,
    DateField,
    Field,
    ValidationError,
    ModelForm,
    Form,
    ModelMultipleChoiceField
)
from django.forms.widgets import DateInput, CheckboxSelectMultiple
from django.forms import TextInput

class SignupForm(BaseUserCreationForm):
    class Meta:
        model = User
        fields = (
            "username",
        )
        

    def save(self, commit=True):
        user = super().save(commit=False)
        user.username = self.cleaned_data["username"]
        if commit:
            user.save()
        return user


class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = (
            # "username",
        )
        

    def save(self, commit=True):
        user = super().save(commit=False)
        user.username = self.cleaned_data["username"]
        if commit:
            user.save()
        return user
    
class AddFilmForm(ModelForm):
    class Meta:
        model = Film
        fields = ["title", "description", "image", "year_created", "genres"]
        
    genres = ModelMultipleChoiceField(
        queryset=Genre.objects.all(),
        widget=CheckboxSelectMultiple
    )
    
    def save(self, commit=True):
        film = super().save(commit=False)
        print(self.cleaned_data)
        for genre in self.cleaned_data["genres"]:
            print(genre)
        if commit:
            film.save()
            film.genres.add(*self.cleaned_data["genres"])
            
        return film
        

DjangoProjectApp/views.py
from typing import Any
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from flask import request
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import UserPassesTestMixin
from DjangoProjectApp.filters import GenreFilter
from DjangoProjectApp.forms import AddFilmForm, LoginForm, SignupForm
from django.views.generic import View, ListView, FormView
from DjangoProjectApp.models.films import Film, Genre
from DjangoProjectApp.models.user import User, Like
from django.contrib.auth import login, logout
from django.contrib import messages
from django.core.paginator import Paginator
from functools import reduce
from django.http import JsonResponse
import operator

# def superuser_required():
#     def wrapper(wrapped):
#         class WrappedClass(UserPassesTestMixin, wrapped):
#             def test_func(self):
#                 return self.request.user.is_superuser

#         return WrappedClass
#     return wrapper




class SignupView(FormView):
    template_name = "DjangoProjectApp/signup.html"
    model = User
    form_class = SignupForm
    success_url = reverse_lazy("main_page")

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return super().form_valid(form)

# class MainView(View):
class AuthenticationView(FormView):
    template_name = "DjangoProjectApp/login.html"
    model = User
    form_class = LoginForm
    success_url = reverse_lazy("main_page")

    def form_valid(self, form):
        login(self.request, form.user_cache)
        return super().form_valid(form)

def logout_page(request):
    logout(request)
    return redirect("main_page")

def main_page(request):
    genres = Genre.objects.all()
    genres_filter = request.GET.getlist("genres")
    films = Film.objects.all()
    min_year_created = request.GET.get('min_year')
    max_year_created = request.GET.get('max_year')

    if min_year_created and max_year_created:
        films = films.filter(year_created__gte=min_year_created, year_created__lte=max_year_created)
    
    if genres_filter:
        querysets = []
        for genre in genres_filter:
            querysets.append(films.filter(genres=genre))
        films = reduce(operator.and_, querysets)

    paginated = Paginator(films, 3)
    page_number = request.GET.get('page')
    
    page = paginated.get_page(page_number)
    # print(films)    
    # for film in films:
    #     print(film.title, film.genres.all())
    return render(request, "DjangoProjectApp/main_page.html", {'genres': genres, 'films': page.object_list, 'page': page})

@login_required(login_url="/login")
def profile_page(request):
    user = request.user
    liked_films = user.liked_films.all()

    return render(request, "DjangoProjectApp/profile_page.html", {'user': user, 'liked_films': liked_films})

class AddFilmView(FormView):
    # if request.user.is_superuser == False:
    #     messages.info(request, 'Вы не Администратор.')
    form_class = AddFilmForm
    model = Film
    template_name = "DjangoProjectApp/add_film.html"
    success_url = reverse_lazy('main_page') 

    def form_valid(self, form: Any) -> HttpResponse:

        if Film.objects.filter(title=form.cleaned_data['title']).exists():
            messages.error(self.request, 'Фильм с таким названием уже существует')
            return super().form_invalid(form)

        form.instance.user = self.request.user
        film = form.save(commit=False)
        film.save()
        form.save_m2m()
        return super().form_valid(form)
    
# class FilmDetailView(View):
#     model = Film
#     template_name = "DjangoProjectApp/film_detail.html"
    
def FilmDetail(request, slug):
    film = Film.objects.get(slug=slug)
    return render(request, 'DjangoProjectApp/film_detail.html', {'film': film})

@user_passes_test(lambda u: u.is_superuser, login_url="/")
def delete_film(request, slug):
    film = get_object_or_404(Film, slug=slug)
    film.delete()
    return redirect('/') 

@login_required
def like_film(request):
    if request.method == 'POST':
        film_id = request.POST.get('film_id')
        film = Film.objects.get(id=film_id)
        user = request.user

        like, created = Like.objects.get_or_create(user=user, film=film)

        if not created:
            like.delete()

        return JsonResponse({'status': 'ok'})

    return JsonResponse({'status': 'error'})

DjangoProjectApp/templates/DjangoProjectApp/add_film.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'DjangoProjectApp/css/styles.css' %}" />
    <link rel="stylesheet" href="{% static 'DjangoProjectApp/css/add_film.css' %}" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Film</title>
</head>
<script>
    function goToPage(url) {
        window.location.href = url;
    }
</script>
<body class="login-body">
    <div class="login-container">
        <h1>Добавить Фильм</h1>
        {% if request.user.is_superuser == False %}
            <p>Вы не Администратор.</p>
        {% else %}
            <form method="POST" enctype="multipart/form-data" class="login-form">
                {% csrf_token %}
                {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                            {% if message.tags %}
                                <li class="{{ message.tags }}">{{ message }}</li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                {% endif %}
                <div class="login-field">
                    <label for="id_title">Название</label>
                    {{ form.title }}
                </div>
                <div class="login-field">
                    <label for="id_image">Превью</label>
                    {{ form.image }}
                </div>
                <div class="login-field">
                    <label for="id_year_created">Год выпуска</label>
                    {{ form.year_created }}
                </div>
                <div class="login-field">
                    <label for="id_genres">Жанры</label>
                    {{ form.genres }}
                </div>
                <div class="login-field">
                    <label for="id_description">Описание</label>
                    {{ form.description }}
                </div>
                <div class="login-field">
                    <input type="submit" value="Сохранить" class="login-button">
                </div>
            </form>
        {% endif %}
    </div>
    <div class="sidebar-buttons">
        <button onclick="goToPage('/')">Меню</button>
        <button onclick="goToPage('/signup')">Регистрация</button>
        <button onclick="goToPage('/login')">Вход</button>
        <button onclick="goToPage('/profile')">Профиль</button>
        {% if request.user.is_superuser == True %}
        <button onclick="goToPage('/add_film')">Добавить фильм</button>
        {% endif %}
        {% if request.user.is_authenticated %}
        <button onclick="goToPage('/logout')">Выход</button>
        {% endif %}
    </div>
</body>
</html>

DjangoProjectApp/templates/DjangoProjectApp/film_detail.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ film.title }}</title>
    <link rel="stylesheet" href="{% static 'DjangoProjectApp/css/main_page.css' %}">
    <link rel="stylesheet" href="{% static 'DjangoProjectApp/css/film_detail.css' %}">
</head>
<body>
    <div class="container">
        <div class="movie-details">
            {% if request.user.is_superuser %}
            <button class="delete-button" onclick="goToPage('delete')">Удалить</button>
            {% endif %}
            <h1 class="movie-title">{{ film.title }}</h1>
            <p class="movie-year">{{ film.year_created }}</p>
            <div class="genres">
                <h2>Жанры:</h2>
                <ul>
                    {% for genre in film.genres.all %}
                        <li>{{ genre.name }}</li>
                    {% endfor %}
                </ul>
            </div>
            <div class="description">
                <h2>Описание:</h2>
                <p>{{ film.description }}</p>
            </div>
            <div class="image">
                <img src="{{ film.image.url }}" alt="{{ film.title }}">
            </div>
        </div>
        <div class="sidebar-buttons">
            <button onclick="goToPage('/')">Меню</button>
            <button onclick="goToPage('/signup')">Регистрация</button>
            <button onclick="goToPage('/login')">Вход</button>
            <button onclick="goToPage('/profile')">Профиль</button>
            <button onclick="goToPage('/add_film')">Добавить фильм</button>
        </div>
    </div>

    <script>
        function goToPage(url) {
            window.location.href = url;
        }
    </script>
</body>
</html>

DjangoProjectApp/templates/DjangoProjectApp/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<script>
    function goToPage(url) {
        window.location.href = url;
    }
</script>
<style>
    /* Стили, которые вы уже использовали для страницы регистрации */
    
</style>
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'DjangoProjectApp/css/main_page.css' %}" />
    <link rel="stylesheet" href="{% static 'DjangoProjectApp/css/login.css' %}" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>

<body class="login-body">
    <div class="login-container">
        <h1>Вход</h1>
        <form method="post" class="login-form">
            {% csrf_token %}
            <div class="login-field">
                <label for="id_username">{{ form.username.label }}</label>
                {{ form.username }}
            </div>
            <div class="login-field">
                <label for="id_password">{{ form.password.label }}</label>
                {{ form.password }}
            </div>
            <div class="login-field">
                <input type="submit" value="Войти" class="login-button">
            </div>
            <div class="login-errors">
                {{ form.errors }}
            </div>
        </form>
    </div>
    <div class="sidebar-buttons">
        <button onclick="goToPage('/')">Меню</button>
        <button onclick="goToPage('/signup')">Регистрация</button>
        <button onclick="goToPage('/login')">Вход</button>
        <button onclick="goToPage('/profile')">Профиль</button>
        {% if request.user.is_superuser == True %}
        <button onclick="goToPage('/add_film')">Добавить фильм</button>
        {% endif %}
        {% if request.user.is_authenticated %}
        <button onclick="goToPage('/logout')">Выход</button>
        {% endif %}
    </div>
</body>

</html>

DjangoProjectApp/templates/DjangoProjectApp/main_page.html
{% load static %}
{% load pagination %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Выбор фильмов</title>
    <link rel="stylesheet" href="{% static 'DjangoProjectApp/css/main_page.css' %}" >
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
    function goToPage(url) {
        window.location.href = url;
    }
    </script>
</head>
<body>
    <div class="container">
        <div class="filters">
            <div class="genres-margin-left">
                <h1>Выберите жанры:</h1>
                <form method="get">
                    <div class="genres-container">
                        {% for genre in genres %}
                            <div class="genre-item">
                                <input type="checkbox" name="genres" value="{{ genre.id }}" id="genre-{{ genre.id }}">
                                <label for="genre-{{ genre.id }}">{{ genre.name }}</label>
                            </div>
                        {% endfor %}
                    </div>
                    <label for="yearRange">Фильтр по году выпуска:</label>
                    <div id="yearRange"></div>
                    <p> </p>
                    <input type="text" id="minYear" name="min_year" readonly>
                    <input type="text" id="maxYear" name="max_year" readonly style="margin-left: 26px;">
                    <br>
                    <p> </p>
                    <input type="submit" value="Применить" style="background-color: #8b31e9; color: #fff; border: none; padding: 10px 158px; border-radius: 5px; cursor: pointer;">
                </form>
            </div>  
        </div>
        <div class="movies">
            {% for film in films %}
                <div class="movie-item">
                    <div>
                        <button class="go-to-button" onclick="goToPage('/film/{{ film.slug }}')">Перейти</button>
                        <h2>{{ film.title }} ({{ film.year_created }})</h2>
                        {% for genre in film.genres.all|slice:":5" %}
                            <span style="display: inline-block; background-color: #211b1f; color: #e8a3c4; padding: 3px 8px; margin-right: 5px; margin-bottom: 5px; border-radius: 5px;">{{ genre.name }}</span>
                        {% endfor %}
                        {% if film.genres.count > 5 %}
                            <span style="display: inline-block; background-color: #211b1f; color: #e8a3c4; padding: 3px 8px; margin-right: 5px; margin-bottom: 5px; border-radius: 5px;">...</span>
                        {% endif %}
                    </div>
                    <img src="{{ film.image.url }}" alt="IMG_ERROR" height="200">
                    <button class="like-button {% if film in request.user.likes_lst.all %}liked{% else %}not-liked{% endif %}" data-film-id="{{ film.id }}">
                        <img src="/static/DjangoProjectApp/img/{% if film in request.user.likes_lst.all %}Filled{% else %}Empty{% endif %}-heart.png" alt="Лайк">
                    </button>
                </div>
            {% endfor %}
        </div>
        <div class="sidebar-buttons">
            <button onclick="goToPage('/')">Меню</button>
            <button onclick="goToPage('/signup')">Регистрация</button>
            <button onclick="goToPage('/login')">Вход</button>
            <button onclick="goToPage('/profile')">Профиль</button>
            {% if request.user.is_superuser %}
            <button onclick="goToPage('/add_film')">Добавить фильм</button>
            {% endif %}
            {% if request.user.is_authenticated %}
            <button onclick="goToPage('/logout')">Выход</button>
            {% endif %}
        </div>
    </div>
    <div class="pagination">
        {% if page.has_previous %}
            <a href="{% get_page_url request 'page' page_obj.previous_page_number %}" class="btn btn-secondary">Previous</a>
        {% endif %}
        
        <a href="{% get_page_url request 'page' 1 %}" class="btn btn-secondary">First</a>

        {% for num in page.paginator.page_range %}
            {% if num == page.number %}
                <span class="btn btn-secondary">{{ num }}</span>
            {% else %}
                <a href="{% get_page_url request 'page' num %}" class="btn btn-secondary">
                    {{ num }}
                </a>
            {% endif %}
        {% endfor %}

        <a href="{% get_page_url request 'page' page.paginator.num_pages %}" class="btn btn-secondary">Last</a>

        {% if page.has_next %}
            <a href="{% get_page_url request 'page' page_obj.next_page_number %}" class="btn btn-secondary">Next</a>
        {% endif %}
    </div>
    <script>
        $(function() {
            $("#yearRange").slider({
                range: true,
                min: 1990,
                max: 2024,
                values: [1990, 2024],
                slide: function(event, ui) {
                    $("#minYear").val(ui.values[0]);
                    $("#maxYear").val(ui.values[1]);
                }
            });
            $("#minYear").val($("#yearRange").slider("values", 0));
            $("#maxYear").val($("#yearRange").slider("values", 1));
        });
    </script>
    <script>
        $(document).ready(function() {
            $(".like-button").click(function(e) {
                e.preventDefault();
                
                const filmId = $(this).data("film-id");

                $.ajax({
                    url: '/like_film/',
                    method: 'POST',
                    data: {
                        'film_id': filmId,
                        'csrfmiddlewaretoken': '{{ csrf_token }}'
                    },
                    success: function(response) {
                        // Обновите DOM или уведомите пользователя
                        if (response.status === 'liked') {
                            alert('Фильм добавлен в список лайкнутых!');
                        } else if (response.status === 'unliked') {
                            alert('Фильм удален из списка лайкнутых!');
                        }
                    },
                    error: function(error) {
                        console.log('Произошла ошибка:', error);
                    }
                });
            });
        });
    </script>
    <script>
        document.addEventListener("DOMContentLoaded", function() {
    const likeButtons = document.querySelectorAll('.like-button');

    likeButtons.forEach(button => {
        button.addEventListener('click', function() {
            const filmId = this.getAttribute('data-film-id');
            const isLiked = this.classList.contains('liked');

            // Здесь можно отправить AJAX-запрос для лайка/анлайка фильма
            // В этом примере просто переключаем классы и меняем состояние сердечка
            if (isLiked) {
                this.classList.remove('liked');
                this.classList.add('not-liked');
                this.querySelector('img').src = "{% static 'DjangoProjectApp\img\Empty-heart.png' %}";
            } else {
                this.classList.remove('not-liked');
                this.classList.add('liked');
                this.querySelector('img').src = "{% static 'DjangoProjectApp\img\Filled-heart.png' %}";
            }
        });
    });
});
    </script>
</body>
</html>

DjangoProjectApp/templates/DjangoProjectApp/profile_page.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Профиль</title>
    <link rel="stylesheet" href="{% static 'DjangoProjectApp/css/main_page.css' %}">
    <link rel="stylesheet" href="{% static 'DjangoProjectApp/css/profile_page.css' %}">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
</head>
<body>
<div class="container">
    <div class="profile-info">
        {{ user.get_username }}
    </div>
    <div class="liked-movies">
        <h1 style="color: rgb(249, 190, 183)">Лайкнутые фильмы</h1>
        {% for film in liked_films %}
        <div class="movie-item">
            <div>
                <button class="go-to-button" onclick="goToPage('/film/{{ film.slug }}')">Перейти</button>
                <h2>{{ film.title }} ({{ film.year_created }})</h2>
                {% for genre in film.genres.all|slice:":5" %}
                    <span style="display: inline-block; background-color: #211b1f; color: #e8a3c4; padding: 3px 8px; margin-right: 5px; margin-bottom: 5px; border-radius: 5px;">{{ genre.name }}</span>
                {% endfor %}
                {% if film.genres.count > 5 %}
                    <span style="display: inline-block; background-color: #211b1f; color: #e8a3c4; padding: 3px 8px; margin-right: 5px; margin-bottom: 5px; border-radius: 5px;">...</span>
                {% endif %}
            </div>
            <img src="{{ film.image.url }}" alt="IMG_ERROR" height="200">
            <button class="like-button {% if film in request.user.likes_lst.all %}liked{% else %}not-liked{% endif %}" data-film-id="{{ film.id }}">
                <img src="/static/DjangoProjectApp/img/{% if film in request.user.likes_lst.all %}Filled{% else %}Empty{% endif %}-heart.png" alt="Лайк">
            </button>
        </div>
        {% endfor %}
    </div>
</div>
<div class="sidebar-buttons">
    <button onclick="goToPage('/')">Меню</button>
    <button onclick="goToPage('/signup')">Регистрация</button>
    <button onclick="goToPage('/login')">Вход</button>
    <button onclick="goToPage('/profile')">Профиль</button>
    {% if request.user.is_superuser == True %}
    <button onclick="goToPage('/add_film')">Добавить фильм</button>
    {% endif %}
    {% if request.user.is_authenticated %}
    <button onclick="goToPage('/logout')">Выход</button>
    {% endif %}
</div>
<script>
    function goToPage(url) {
        window.location.href = url;
    }
</script>
<script>
    $(document).ready(function() {
        $('.like-button').on('click', function() {
            var film_id = $(this).data('film-id');
            var csrf_token = '{{ csrf_token }}';

            $.ajax({
                url: '/like_film/',
                method: 'POST',
                data: {
                    'film_id': film_id,
                    'csrfmiddlewaretoken': csrf_token
                },
                success: function(response) {
                    if (response.status === 'ok') {
                        // Обновляем состояние кнопки или что-то еще
                    }
                },
                error: function() {
                    alert('Произошла ошибка при отправке запроса.');
                }
            });
        });
    });
</script>
<script>
    document.addEventListener("DOMContentLoaded", function() {
const likeButtons = document.querySelectorAll('.like-button');

likeButtons.forEach(button => {
    button.addEventListener('click', function() {
        const filmId = this.getAttribute('data-film-id');
        const isLiked = this.classList.contains('liked');

        // Здесь можно отправить AJAX-запрос для лайка/анлайка фильма
        // В этом примере просто переключаем классы и меняем состояние сердечка
        if (isLiked) {
            this.classList.remove('liked');
            this.classList.add('not-liked');
            this.querySelector('img').src = "{% static 'DjangoProjectApp\img\Empty-heart.png' %}";
        } else {
            this.classList.remove('not-liked');
            this.classList.add('liked');
            this.querySelector('img').src = "{% static 'DjangoProjectApp\img\Filled-heart.png' %}";
        }
    });
});
});
</script>
</html>